"""add_image_style_to_sentence

Revision ID: 1e5a124bd2ca
Revises: 005
Create Date: 2025-11-24 16:47:28.554308

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1e5a124bd2ca'
down_revision = '005'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """升级数据库结构"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('api_keys', 'last_used_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_comment='最后使用时间',
               existing_nullable=True)
    op.alter_column('api_keys', 'id',
               existing_type=sa.UUID(),
               comment='主键ID',
               existing_comment='API密钥唯一标识',
               existing_nullable=False)
    op.alter_column('api_keys', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               type_=sa.DateTime(timezone=True),
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('api_keys', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               type_=sa.DateTime(timezone=True),
               existing_comment='更新时间',
               existing_nullable=False)
    op.alter_column('chapters', 'project_id',
               existing_type=sa.UUID(),
               comment='项目外键',
               existing_comment='外键索引，无约束',
               existing_nullable=False)
    op.alter_column('chapters', 'content',
               existing_type=sa.TEXT(),
               comment='章节原始内容',
               existing_comment='章节内容',
               existing_nullable=False)
    op.alter_column('chapters', 'is_confirmed',
               existing_type=sa.BOOLEAN(),
               comment='是否已确认',
               existing_comment='是否确认',
               existing_nullable=True)
    op.alter_column('chapters', 'confirmed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_comment='确认时间',
               existing_nullable=True)
    op.alter_column('chapters', 'edited_content',
               existing_type=sa.TEXT(),
               comment='用户编辑后的内容',
               existing_comment='编辑后的内容',
               existing_nullable=True)
    op.alter_column('chapters', 'generation_settings',
               existing_type=sa.TEXT(),
               comment='章节级生成配置',
               existing_comment='JSON格式生成配置',
               existing_nullable=True)
    op.alter_column('chapters', 'video_url',
               existing_type=sa.VARCHAR(length=500),
               comment='最终视频URL',
               existing_comment='生成的视频URL',
               existing_nullable=True)
    op.alter_column('chapters', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('chapters', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_comment='更新时间',
               existing_nullable=False)
    op.create_index(op.f('ix_chapters_project_id'), 'chapters', ['project_id'], unique=False)
    op.create_index(op.f('ix_chapters_status'), 'chapters', ['status'], unique=False)
    op.create_foreign_key(None, 'chapters', 'projects', ['project_id'], ['id'])
    op.drop_table_comment(
        'chapters',
        existing_comment='章节表',
        schema=None
    )
    op.alter_column('paragraphs', 'chapter_id',
               existing_type=sa.UUID(),
               comment='章节外键',
               existing_comment='外键索引，无约束',
               existing_nullable=False)
    op.alter_column('paragraphs', 'action',
               existing_type=sa.VARCHAR(length=10),
               comment='操作类型',
               existing_comment='操作类型: keep, edit, delete, ignore',
               existing_nullable=True)
    op.alter_column('paragraphs', 'is_confirmed',
               existing_type=sa.BOOLEAN(),
               comment='是否已确认',
               existing_comment='是否确认',
               existing_nullable=True)
    op.alter_column('paragraphs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('paragraphs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_comment='更新时间',
               existing_nullable=False)
    op.create_index(op.f('ix_paragraphs_action'), 'paragraphs', ['action'], unique=False)
    op.create_index(op.f('ix_paragraphs_chapter_id'), 'paragraphs', ['chapter_id'], unique=False)
    op.create_foreign_key(None, 'paragraphs', 'chapters', ['chapter_id'], ['id'])
    op.drop_table_comment(
        'paragraphs',
        existing_comment='段落表',
        schema=None
    )
    op.alter_column('projects', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment='处理状态',
               existing_comment='项目处理状态: uploaded, parsing, parsed, generating, completed, failed, archived',
               existing_nullable=True)
    op.alter_column('projects', 'completed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_comment='完成时间',
               existing_nullable=True)
    op.alter_column('projects', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('projects', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_comment='更新时间',
               existing_nullable=False)
    op.drop_table_comment(
        'projects',
        existing_comment='项目表',
        schema=None
    )
    op.add_column('sentences', sa.Column('image_style', sa.String(length=100), nullable=True, comment='图片风格'))
    op.alter_column('sentences', 'paragraph_id',
               existing_type=sa.UUID(),
               comment='段落外键',
               existing_comment='外键索引，无约束',
               existing_nullable=False)
    op.alter_column('sentences', 'character_count',
               existing_type=sa.INTEGER(),
               comment='字符数量',
               existing_comment='字符数统计',
               existing_nullable=True)
    op.alter_column('sentences', 'voice_settings',
               existing_type=sa.TEXT(),
               comment='JSON格式的语音合成参数',
               existing_comment='JSON格式语音合成参数',
               existing_nullable=True)
    op.alter_column('sentences', 'completed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_comment='完成时间',
               existing_nullable=True)
    op.alter_column('sentences', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('sentences', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_comment='更新时间',
               existing_nullable=False)
    op.create_index(op.f('ix_sentences_paragraph_id'), 'sentences', ['paragraph_id'], unique=False)
    op.create_index(op.f('ix_sentences_status'), 'sentences', ['status'], unique=False)
    op.create_foreign_key(None, 'sentences', 'paragraphs', ['paragraph_id'], ['id'])
    op.drop_table_comment(
        'sentences',
        existing_comment='句子表',
        schema=None
    )
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_comment='更新时间',
               existing_nullable=False)
    op.drop_constraint(op.f('uq_users_email'), 'users', type_='unique')
    op.drop_constraint(op.f('uq_users_username'), 'users', type_='unique')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.drop_table_comment(
        'users',
        existing_comment='用户表',
        schema=None
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """降级数据库结构"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table_comment(
        'users',
        '用户表',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_unique_constraint(op.f('uq_users_username'), 'users', ['username'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('uq_users_email'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_comment='更新时间',
               existing_nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_comment='创建时间',
               existing_nullable=False)
    op.create_table_comment(
        'sentences',
        '句子表',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint(None, 'sentences', type_='foreignkey')
    op.drop_index(op.f('ix_sentences_status'), table_name='sentences')
    op.drop_index(op.f('ix_sentences_paragraph_id'), table_name='sentences')
    op.alter_column('sentences', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_comment='更新时间',
               existing_nullable=False)
    op.alter_column('sentences', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('sentences', 'completed_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_comment='完成时间',
               existing_nullable=True)
    op.alter_column('sentences', 'voice_settings',
               existing_type=sa.TEXT(),
               comment='JSON格式语音合成参数',
               existing_comment='JSON格式的语音合成参数',
               existing_nullable=True)
    op.alter_column('sentences', 'character_count',
               existing_type=sa.INTEGER(),
               comment='字符数统计',
               existing_comment='字符数量',
               existing_nullable=True)
    op.alter_column('sentences', 'paragraph_id',
               existing_type=sa.UUID(),
               comment='外键索引，无约束',
               existing_comment='段落外键',
               existing_nullable=False)
    op.drop_column('sentences', 'image_style')
    op.create_table_comment(
        'projects',
        '项目表',
        existing_comment=None,
        schema=None
    )
    op.alter_column('projects', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_comment='更新时间',
               existing_nullable=False)
    op.alter_column('projects', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('projects', 'completed_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_comment='完成时间',
               existing_nullable=True)
    op.alter_column('projects', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment='项目处理状态: uploaded, parsing, parsed, generating, completed, failed, archived',
               existing_comment='处理状态',
               existing_nullable=True)
    op.create_table_comment(
        'paragraphs',
        '段落表',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint(None, 'paragraphs', type_='foreignkey')
    op.drop_index(op.f('ix_paragraphs_chapter_id'), table_name='paragraphs')
    op.drop_index(op.f('ix_paragraphs_action'), table_name='paragraphs')
    op.alter_column('paragraphs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_comment='更新时间',
               existing_nullable=False)
    op.alter_column('paragraphs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('paragraphs', 'is_confirmed',
               existing_type=sa.BOOLEAN(),
               comment='是否确认',
               existing_comment='是否已确认',
               existing_nullable=True)
    op.alter_column('paragraphs', 'action',
               existing_type=sa.VARCHAR(length=10),
               comment='操作类型: keep, edit, delete, ignore',
               existing_comment='操作类型',
               existing_nullable=True)
    op.alter_column('paragraphs', 'chapter_id',
               existing_type=sa.UUID(),
               comment='外键索引，无约束',
               existing_comment='章节外键',
               existing_nullable=False)
    op.create_table_comment(
        'chapters',
        '章节表',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint(None, 'chapters', type_='foreignkey')
    op.drop_index(op.f('ix_chapters_status'), table_name='chapters')
    op.drop_index(op.f('ix_chapters_project_id'), table_name='chapters')
    op.alter_column('chapters', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_comment='更新时间',
               existing_nullable=False)
    op.alter_column('chapters', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('chapters', 'video_url',
               existing_type=sa.VARCHAR(length=500),
               comment='生成的视频URL',
               existing_comment='最终视频URL',
               existing_nullable=True)
    op.alter_column('chapters', 'generation_settings',
               existing_type=sa.TEXT(),
               comment='JSON格式生成配置',
               existing_comment='章节级生成配置',
               existing_nullable=True)
    op.alter_column('chapters', 'edited_content',
               existing_type=sa.TEXT(),
               comment='编辑后的内容',
               existing_comment='用户编辑后的内容',
               existing_nullable=True)
    op.alter_column('chapters', 'confirmed_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_comment='确认时间',
               existing_nullable=True)
    op.alter_column('chapters', 'is_confirmed',
               existing_type=sa.BOOLEAN(),
               comment='是否确认',
               existing_comment='是否已确认',
               existing_nullable=True)
    op.alter_column('chapters', 'content',
               existing_type=sa.TEXT(),
               comment='章节内容',
               existing_comment='章节原始内容',
               existing_nullable=False)
    op.alter_column('chapters', 'project_id',
               existing_type=sa.UUID(),
               comment='外键索引，无约束',
               existing_comment='项目外键',
               existing_nullable=False)
    op.alter_column('api_keys', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               server_default=sa.text('now()'),
               type_=postgresql.TIMESTAMP(),
               existing_comment='更新时间',
               existing_nullable=False)
    op.alter_column('api_keys', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               server_default=sa.text('now()'),
               type_=postgresql.TIMESTAMP(),
               existing_comment='创建时间',
               existing_nullable=False)
    op.alter_column('api_keys', 'id',
               existing_type=sa.UUID(),
               comment='API密钥唯一标识',
               existing_comment='主键ID',
               existing_nullable=False)
    op.alter_column('api_keys', 'last_used_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_comment='最后使用时间',
               existing_nullable=True)
    # ### end Alembic commands ###